import {
  type LucideIcon,
  Github,
  Twitter,
  Linkedin,
  Instagram,
  Facebook,
  Menu,
  X,
  Sun,
  Moon,
  Laptop,
  CheckCircle2,
  MailIcon,
  User,
  MessageSquare,
  ArrowRight,
  BookOpen,
  Share2,
  Download,
  RefreshCw,
  Printer,
  Settings,
  Plus,
  Trash2,
  Edit,
  GripVertical,
  ChevronLeft,
  ChevronRight,
  Search,
  Copy,
  ExternalLink,
  Calendar,
  CalendarCheck2,
  Clock,
  MapPin,
  FileText,
  Code,
  Palette,
  Server,
  Database,
  Cloud,
  Terminal,
  BrainCircuit,
  Bot,
  PenTool,
  Briefcase,
  GraduationCap,
  Sparkles,
  Link,
  Eye,
  EyeOff,
  Book,
  Tag,
  Tags,
  Rss,
  Home,
  UserCircle,
  FolderGit2,
  Building2,
  Loader2,
  Send,
  Construction,
  Layers,
  MoveUp,
  MoveDown,
  Phone,
} from "lucide-react"

export type Icon = LucideIcon

const baseIcons: Record<string, LucideIcon> = {
  // social
  gitHub: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  instagram: Instagram,
  facebook: Facebook,
  mail: MailIcon,
  phone: Phone,

  // ui
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  checkCircle: CheckCircle2,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  copy: Copy,
  externalLink: ExternalLink,
  printer: Printer,
  calendarCheck: CalendarCheck2,
  download: Download,
  share: Share2,
  settings: Settings,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  gripVertical: GripVertical,
  search: Search,
  refreshCw: RefreshCw,
  spinner: Loader2,
  send: Send,
  construction: Construction,
  moveUp: MoveUp,
  moveDown: MoveDown,

  // navigation & content
  home: Home,
  user: User,
  contact: MessageSquare,
  messageSquare: MessageSquare,
  briefcase: Briefcase,
  palette: Palette,
  architecture: Building2,
  blog: BookOpen,
  fileText: FileText,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  code: Code,
  server: Server,
  database: Database,
  cloud: Cloud,
  terminal: Terminal,
  brainCircuit: BrainCircuit,
  bot: Bot,
  penTool: PenTool,
  graduationCap: GraduationCap,
  sparkles: Sparkles,
  link: Link,
  eye: Eye,
  eyeOff: EyeOff,
  book: Book,
  tag: Tag,
  tags: Tags,
  rss: Rss,
  userCircle: UserCircle,
  folderGit: FolderGit2,
  layers: Layers,
}

/** Pascal-case aliases (Plus, ExternalLink, …)  */
const Icons: Record<string, LucideIcon> = { ...baseIcons }

for (const key of Object.keys(baseIcons)) {
  const pascal = key.charAt(0).toUpperCase() + key.slice(1)
  if (!Icons[pascal]) Icons[pascal] = baseIcons[key]
}

export { Icons }
