"use client"

import type { SVGProps, FC } from "react"
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BarChart,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  FastForward,
  File,
  FileText,
  Github,
  GripVertical,
  Home,
  ImageIcon,
  Instagram,
  Layers,
  Laptop,
  LineChart,
  Linkedin,
  List,
  ListOrdered,
  Loader2,
  Mail,
  MapPin,
  Menu,
  Moon,
  Palette,
  Pause,
  Phone,
  PieChart,
  Pizza,
  Play,
  Printer,
  RefreshCw,
  Rewind,
  Send,
  Search,
  SearchX,
  Server,
  Sparkles,
  SunMedium,
  Tag,
  Trash,
  Twitter,
  Wand2,
  Zap,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Expand,
  Users,
  Clock,
  Construction,
} from "lucide-react"

/* -------------------------------------------------------------------------- */
/*                                   Branding                                 */
/* -------------------------------------------------------------------------- */
const Logo: FC<SVGProps<SVGSVGElement>> = (props) => (
  <Sparkles {...props} className={`h-6 w-6 ${props.className ?? ""}`} />
)

/* -------------------------------------------------------------------------- */
/*                                  Icon Map                                  */
/* -------------------------------------------------------------------------- */
export const Icons = {
  /* Navigation & Sections */
  home: Home,
  briefcase: Briefcase,
  code: Code,
  architecture: Building2,
  fileText: FileText,
  bookOpen: BookOpen,
  palette: Palette,
  contact: Mail,

  /* UI Controls & Common */
  menu: Menu,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  sun: SunMedium,
  moon: Moon,
  search: Search,
  searchX: SearchX,
  copy: Copy,
  check: Check,
  checkCircle: CheckCircle2,
  spinner: Loader2,
  warning: AlertTriangle,
  externalLink: ExternalLink,
  construction: Construction,
  refreshCw: RefreshCw,
  send: Send,
  rotateCw: RotateCw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  expand: Expand,
  download: Download,
  printer: Printer,
  edit: Edit,
  trash: Trash,
  list: List,
  listOrdered: ListOrdered,
  play: Play,
  pause: Pause,
  rewind: Rewind,
  fastForward: FastForward,
  gripVertical: GripVertical,

  /* Forms & Data */
  calendar: Calendar,
  calendarCheck: CalendarCheck2,
  clock: Clock,
  tag: Tag,
  file: File,
  creditCard: CreditCard,

  /* Contact / Location */
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,

  /* Social */
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  instagram: Instagram,
  x: Twitter, // alias for "x" social icon

  /* Tech / Misc */
  laptop: Laptop,
  cpu: Cpu,
  database: Database,
  server: Server,
  zap: Zap,
  lineChart: LineChart,
  barChart: BarChart,
  pieChart: PieChart,
  activity: Activity,
  layers: Layers,
  brain: BrainCircuit,
  bot: BrainCircuit,
  generator: Wand2,
  image: ImageIcon,
  users: Users,
  pizza: Pizza,

  /* Branding */
  logo: Logo,
  sparkles: Sparkles,
} as const

export type IconName = keyof typeof Icons
